djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from django.urls import path, include

# from leads.views import home_page
from leads.views import HomePageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads import views
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView

app_name = 'leads'

urlpatterns = [
    path('leads_all/', LeadListView.as_view(), name='lead_list'),
    # path('leads_all/', views.lead_list, name='lead_list'),

    path('categories_all/', CategoryListView.as_view(), name='category_list'),
    path('category_detail/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:pk>/lead_category_update/', LeadCategoryUpdateView.as_view(), name='lead_category_update'),

    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    # path('<int:pk>/', views.lead_detail, name='lead_detail'),

    path('lead_create/', LeadCreateView.as_view(), name='lead_create'),
    # path('leads_create/', views.lead_create, name='lead_create'),
    path('<int:pk>/lead_assign_agent/', AssignAgentView.as_view(), name='lead_assign_agent'),

    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead_update'),
    # path('<int:pk>/update', views.lead_update, name='lead_update'),

    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead_delete'),
#     path('<int:pk>/delete', views.lead_delete, name='lead_delete'),
]

leads/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


    
class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=18)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey("Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey('Category',related_name='leads', null=True, blank=True, on_delete=models.SET_NULL)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.category}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} - {self.user.email} - org: {self.organization}"
    
class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Categories"

    
def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
    

post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

from .models import Lead, Agent

User = get_user_model()

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            "first_name",
            "last_name",
            "age",
            "agent",
            "description",
            "phone",
            "email"
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=18)

class AssignAgentFrom(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentFrom, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = ("category",)

leads/views.py
from typing import Any
from django.core.mail import send_mail
from django.db.models.base import Model as Model
from django.db.models.query import QuerySet
from django.shortcuts import render, redirect, reverse
from django.views import generic
from agents.mixins import OrganizerLoginRequiredMixin
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import LeadForm, AssignAgentFrom,  LeadModelForm, CustomUserCreationForm, LeadCategoryUpdateForm
from .models import Lead, Agent, Category

class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse('login')

class HomePageView(generic.TemplateView):
    template_name = 'home_page.html'

# def home_page(request):
#     return render(request, 'home_page.html')


class LeadListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/lead_list.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile, agent__isnull=True)
            context.update({
                'unassigned_leads': queryset
            })
        return context



# def lead_list(request):
#     leads = Lead.objects.all()

#     context = {"leads": leads}

#     return render(request, 'leads/lead_list.html', context)


class LeadDetailView(OrganizerLoginRequiredMixin, generic.DetailView):
    template_name = 'leads/lead_detail.html'
    queryset = Lead.objects.all()
    context_object_name = 'lead'

# def lead_detail(request, pk):
#     lead = Lead.objects.get(id=pk)

#     context = {"lead": lead}

#     return render(request, 'leads/lead_detail.html', context)


class LeadCreateView(OrganizerLoginRequiredMixin, generic.CreateView):
    template_name = 'leads/lead_create.html'
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:lead_list')
    
    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile
        lead.save()
        send_mail(
            subject='A lead has been created',
            message='Check your new lead',
            from_email='text@text.com',
            recipient_list=['test@test.com']
        )
        return super(LeadCreateView, self).form_valid(form)
    

# def lead_create(request):
#     form = LeadModelForm()
#     if request.method == 'POST':
#         form = LeadModelForm(request.POST)
#         if form.is_valid():
#             form.save()
#             return redirect('leads:lead_list')

    # context = {'form': form}
    # return render(request, 'leads/lead_create.html', context)

# def lead_create(request):
#     form = LeadForm()
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()
#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent
#             )
#             return redirect('leads:lead_list')

#     context = {'form': form}
#     return render(request, 'leads/lead_create.html', context)


class LeadUpdateView(OrganizerLoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_update.html'
    queryset = Lead.objects.all()
    form_class = LeadModelForm

    def get_success_url(self):
        return reverse('leads:lead_list')
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)
    

# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadModelForm(instance=lead)
#     if request.method == 'POST':
#         form = LeadModelForm(request.POST, instance=lead)
#         if form.is_valid():
#             form.save()
#             return redirect('leads:lead_list')

#     context = {
#         "lead": lead,
#         "form": form
#         }

#     return render(request, 'leads/lead_update.html', context)

# def lead_update(request, pk):
#     lead = Lead.objects.get(id=pk)
#     form = LeadForm()
#     if request.method == 'POST':
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()
#             lead.first_name=first_name,
#             lead.last_name=last_name,
#             lead.age=age,
#             lead.agent=agent
#             lead.save()
#             return redirect('leads:lead_list')

#     context = {
#         "lead": lead,
#         "form": form
#         }

#     return render(request, 'leads/lead_update.html', context)


class LeadDeleteView(OrganizerLoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/lead_delete.html'
    queryset = Lead.objects.all()

    def get_success_url(self):
        return reverse('leads:lead_list')
    
    def get_queryset(self):
        user = self.request.user
        return Lead.objects.filter(organization=user.userprofile)

# def lead_delete(request, pk):
#     lead = Lead.objects.get(id=pk)
#     lead.delete()
#     return redirect('leads:lead_list')


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead_category_update.html'
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)
        return queryset
    
    def get_success_url(self):
        return reverse('leads:lead_detail', kwargs={'pk': self.get_object().id})
    

class AssignAgentView(OrganizerLoginRequiredMixin, generic.FormView):
    template_name = 'leads/lead_assign_agent.html'
    form_class = AssignAgentFrom

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({'request': self.request})
        return kwargs

    def get_success_url(self):
        return reverse('leads:lead_list')
    
    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        lead = Lead.objects.get(id=self.kwargs['pk'])
        lead.agent = agent
        lead.save()
        return super(AssignAgentView, self).form_valid(form)
    
class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/category_list.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.organization)

        context.update({
            'unassigned_lead_count': queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)
        return queryset
    
class CategoryDetailView(LoginRequiredMixin, generic.DeleteView):
    template_name = 'leads/category_detail.html'
    context_object_name = 'category' 

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(organization=user.userprofile)
        else:
            queryset = Category.objects.filter(organization=user.agent.organization)
        return queryset
    

leads/templates/leads/category_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">{{ category.name }}</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These are the leads under this category</p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">First Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Agent</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Last Category</th>
            </tr>
          </thead>
          <tbody>
            {% for lead in category.leads.all %}
                <tr>
                    <td class="px-4 py-3"><a class="hover:text-blue-500" href="{% url 'leads:lead_detail' lead.id %}">{{ lead.first_name }}</a></td>
                    <td class="px-4 py-3"><a class="hover:text-blue-500" href="{% url 'leads:lead_detail' lead.id %}">{{ lead.last_name }}</a></td>
                    <td class="px-4 py-3">{{ lead.agent }}</td>
                    <td class="px-4 py-3">{{ lead.category }}</td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock %}

leads/templates/leads/category_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="flex flex-col text-center w-full mb-20">
        <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
        <p class="lg:w-2/3 mx-auto leading-relaxed text-base">These categories segment the lead</p>
      </div>
      <div class="lg:w-2/3 w-full mx-auto overflow-auto">
        <table class="table-auto w-full text-left whitespace-no-wrap">
          <thead>
            <tr>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">Name</th>
              <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">Lead Count</th>
            </tr>
          </thead>
          <tbody>
            <tr>
                <td class="px-4 py-3"><a href="{% url 'leads:lead_list' %}">Unassigned</a></td>
                <td class="px-4 py-3">{{ unassigned_lead_count }}</td>
            </tr>
            {% for category in category_list %}
                <tr>
                  <td class="px-4 py-3"><a href="{% url 'leads:category_detail' category.id %}">{{ category.name }}</a></td>
                  <td class="px-4 py-3"><a href="{% url 'leads:category_detail' category.id %}">TODO count</a></td>
                </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </section>

{% endblock %}

leads/templates/leads/lead_assign_agent.html
{% extends 'base.html' %}

{% block content %}
    <div>
        <h1>Assign Agent</h1>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Assign</button>
        </form>
        <hr>
        <div>
            <a href="{% url 'leads:lead_list' %}">Back To List</a>
        </div>
 
    </div>
{% endblock %}

leads/templates/leads/lead_category_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'leads:lead_detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow text-indigo-500 border-b-2 border-gray-300 border-indigo-500 py-2 text-lg px-1" href="{% url 'leads:lead_category_update' lead.id %}">Category</a>
            <a href="{% url 'leads:lead_update' lead.id %}" class="flex-grow border-b-2 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">Update</button>
          </form>
            <div class="mt-3 border-t border-gray-300">
              <button class="text-white w-full bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md mt-3"><a href="{% url 'leads:lead_delete' lead.id %}">Delete</a></button>
            </div>
          </div>
      </div>
    </div>
  </section>
    <div>
        <h1>This is the Lead Detail</h1>
        <div class="lead">
            <p>{{ lead.first_name }} {{ lead.last_name }} - {{ lead.agent }}</p>
        </div>
        <hr>
        <hr>
            <a href="{% url 'leads:lead_delete' lead.id %}">Delete</a>
        <hr>
        <div>
            <a href="{% url 'leads:lead_list' %}">Back To List</a>
        </div>
 
    </div>
    <div>
        <h1>Update Lead : {{ lead.first_name }} {{ lead.last_name }}</h1>
        
        <hr>
        <div>
            <a href="{% url 'leads:lead_list' %}">Back To List</a>
        </div>
 
    </div>
{% endblock %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'leads:lead_detail' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" href="{% url 'leads:lead_category_update' lead.id  %}">Category</a>
            <a href="{% url 'leads:lead_update' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <p class="leading-relaxed mb-4">{{ lead.description }}</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Age</span>
            <span class="ml-auto text-gray-900">{{ lead.age }}</span>
          </div>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">created_at</span>
            <span class="ml-auto text-gray-900">{{ lead.created_at }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell Phone</span>
            <span class="ml-auto text-gray-900">{{ lead.phone }}</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Email</span>
            <span class="ml-auto text-gray-900">{{ lead.email }}</span>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
          <h1 class="text-4xl text-gray-800">Leads</h1>
          <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:category_list' %}">View Categories</a>
      </div>
      {% if request.user.is_organizer %}
        <div>
            <a class="text-gray-500 hover:text-blue-500" href="{% url 'leads:lead_create' %}">Create A New Lead</a>
        </div>
      {% endif %}
    </div>
    <div class="flex flex-wrap -m-4">
      {% for lead in leads %}
      <div class="lead p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><a href="{% url 'leads:lead_detail' lead.id %}">{{ lead.first_name }} {{ lead.last_name }}</a>
            </h2>
            <p class="leading-relaxed text-base">Agent: {{ lead.agent }}</p>
            <p class="leading-relaxed text-base">Age: {{ lead.age }}</p>
            <p class="leading-relaxed text-base">Category: {{ lead.category }}</p>
            <hr>
            <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'leads:lead_detail' lead.id %}">View this lead</a></button>
            <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'leads:lead_update' lead.id %}">Update</a>
            </a></button>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
    <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
      <div>
        <h1 class="text-4xl text-gray-800">Unassigned Leads</h1>
      </div>
    </div>
    <div class="flex flex-wrap -m-4">
      {% if unassigned_leads.exists %}
      {% for lead in unassigned_leads %}
      <div class="lead p-4 lg:w-1/2 md:w-full">
        <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
          <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
              <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
            </svg>
          </div>
          <div class="flex-grow">
            <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><a href="{% url 'leads:lead_detail' lead.id %}">{{ lead.first_name }} {{ lead.last_name }}</a>
            </h2>
            <hr>
            <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'leads:lead_assign_agent' lead.id %}">Assign</a></button>
            <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'leads:lead_update' lead.id %}">Update</a>
            </a></button>
          </div>
        </div>
      </div>
      {% endfor %}
      {% endif %}
    </div>
  </div>
</section>
{% endblock %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Lead</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ lead.first_name }} {{ lead.last_name }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'leads:lead_detail' lead.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1" href="{% url 'leads:lead_category_update' lead.id  %}">Category</a>
            <a href="{% url 'leads:lead_update' lead.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">Update</button>
          </form>
          <div class="mt-3 border-t border-gray-300">
            <button class="text-white w-full bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md mt-3"><a href="{% url 'leads:lead_delete' lead.id %}">Delete</a></button>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}