agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('agent_create/', AgentCreateView.as_view(), name='agent_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent_update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent_delete'),

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from django.urls import path, include

# from leads.views import home_page
from leads.views import HomePageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email', 
            )

agents/views.py
from django.shortcuts import render, reverse
from django.core.mail import send_mail
from django.views import generic
import random

from leads.models import Agent
from .mixins import OrganizerLoginRequiredMixin
from .forms import AgentModelForm

class AgentListView(OrganizerLoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"
    context_object_name = 'agents'

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)
    
class AgentDetailView(OrganizerLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent_detail.html'
    context_object_name = 'agent'

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

class AgentCreateView(OrganizerLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent_create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent_list')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f'{random.randint(1, 10000000)}')
        user.save()
        Agent.objects.create(
            user=user,
            organization=self.request.user.userprofile
        )
        send_mail(
            subject='You are invited to be an agent.',
            message='Check your email to start to work as an agent with DJCRM',
            from_email='text@text.com',
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)



class AgentUpdateView(OrganizerLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent_update.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent_list')
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

    

class AgentDeleteView(OrganizerLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent_delete.html'

    def get_success_url(self):
        return reverse('agents:agent_list')
    
    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

agents/templates/agents/agent_create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <h2 class="text-3xl text-gray-800">Create A New Agent</h2>
        <form method="post" class="mt-5">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Create</button>
        </form>
        <div class="py-5 border-t border-gray-200 mt-5">
            <a class="hover:text-blue-500 mt-5" href="{% url 'agents:agent_list' %}">Back To Agents</a>
        </div>
</div>
{% endblock %}

agents/templates/agents/agent_delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h2 class="text-3xl text-gray-800">Are you sure to delete?</h2>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Delete</button>
    </form>
    <div class="py-5 border-t border-gray-200 mt-5">
        <a class="hover:text-blue-500 mt-5" href="{% url 'agents:agent_detail' agent.id %}">Back to agent</a>
    </div>
</div>
    
{% endblock %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }} {{ agent.organization }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent_detail' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
            <a href="{% url 'agents:agent_update' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update</a>
          </div>
          <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
          <div class="flex border-t border-gray-200 py-2">
            <span class="text-gray-500">Location</span>
            <span class="ml-auto text-gray-900">Dummy Location</span>
          </div>
          <div class="flex border-t border-b mb-6 border-gray-200 py-2">
            <span class="text-gray-500">Cell Phone</span>
            <span class="ml-auto text-gray-900">+01234556</span>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

agents/templates/agents/agent_list.html
{% extends  'base.html' %}

{% block content %}
<section class="text-gray-600 body-font"></section>
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Here are our agents</h1>
            </div>
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'agents:agent_create' %}">Create A New Agent</a>
            </div>
        </div>
        
      <div class="flex flex-wrap -m-4">
        {% for agent in object_list %}
        <div class="lead p-4 lg:w-1/2 md:w-full">
          <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
            <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
              <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
              </svg>
            </div>
            <div class="flex-grow">
              <h2 class="text-gray-900 text-lg title-font font-medium mb-3"><a href="#">{{ agent.user.username }} - {{ agent.organization }}</a>
              </h2>
              <p class="leading-relaxed text-base">Blue bottle crucifix vinyl post-ironic four dollar toast vegan taxidermy. Gastropub indxgo juice poutine.</p>
              <hr>
              <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'agents:agent_detail' agent.id %}">More</a></button>
              <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"><a class="text-indigo-500 inline-flex items-center"><a href="{% url 'agents:agent_update' agent.id %}">Update</a>
              </a></button>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <hr>
    
</section>
{% endblock %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-3/5 mx-auto flex flex-wrap">
        <div class="lg:w-full w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
          <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
          <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ agent.user.username }}</h1>
          <div class="flex mb-4">
            <a href="{% url 'agents:agent_detail' agent.id %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>
            <a href="{% url 'agents:agent_update' agent.id %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update</a>
          </div>
          <form method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <button class="text-white w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md" type="submit">Update</button>
            </form>
            <div class="mt-3 border-t border-gray-300">
              <button class="text-white w-full bg-red-500 hover:bg-red-600 px-3 py-2 rounded-md mt-3"><a href="{% url 'agents:agent_delete' agent.id %}">Delete</a></button>
            </div>
        </div>
      </div>
    </div>
  </section>
   
{% endblock %}