agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent_list'),
    path('agent_create/', AgentCreateView.as_view(), name='agent_create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent_detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent_update'),
    path('<int:pk>/delete/', AgentDeleteView.as_view(), name='agent_delete'),

]

djcrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView

from django.urls import path, include

# from leads.views import home_page
from leads.views import HomePageView, SignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomePageView.as_view(), name='home'),
    path('leads/', include('leads.urls', namespace='leads')),
    path('agents/', include('agents.urls', namespace='agents')),
    path('signup/', SignupView.as_view(), name='signup'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password_reset/', PasswordResetView.as_view(), name='password_reset'),
    path('password_reset_done/', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset_complete/', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from leads import views
from .views import LeadListView, LeadDetailView, LeadCreateView, LeadUpdateView, LeadDeleteView, AssignAgentView, CategoryListView, CategoryDetailView, LeadCategoryUpdateView

app_name = 'leads'

urlpatterns = [
    path('leads_all/', LeadListView.as_view(), name='lead_list'),
    # path('leads_all/', views.lead_list, name='lead_list'),

    path('categories_all/', CategoryListView.as_view(), name='category_list'),
    path('category_detail/<int:pk>/', CategoryDetailView.as_view(), name='category_detail'),
    path('<int:pk>/lead_category_update/', LeadCategoryUpdateView.as_view(), name='lead_category_update'),

    path('<int:pk>/', LeadDetailView.as_view(), name='lead_detail'),
    # path('<int:pk>/', views.lead_detail, name='lead_detail'),

    path('lead_create/', LeadCreateView.as_view(), name='lead_create'),
    # path('leads_create/', views.lead_create, name='lead_create'),
    path('<int:pk>/lead_assign_agent/', AssignAgentView.as_view(), name='lead_assign_agent'),

    path('<int:pk>/update/', LeadUpdateView.as_view(), name='lead_update'),
    # path('<int:pk>/update', views.lead_update, name='lead_update'),

    path('<int:pk>/delete/', LeadDeleteView.as_view(), name='lead_delete'),
#     path('<int:pk>/delete', views.lead_delete, name='lead_delete'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJANGO - CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include 'navbar.html' %}
    <div class="max-w-7xl mx-auto ">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/home_page.html
{% extends 'base.html' %}

{% block content %}

<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
      <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero" src="https://dummyimage.com/720x600">
      <div class="text-center lg:w-2/3 w-full">
        <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">This is the home page</h1>
        <p class="mb-8 leading-relaxed">Meggings kinfolk echo park stumptown DIY, kale chips beard jianbing tousled. Chambray dreamcatcher trust fund, kitsch vice godard disrupt ramps hexagon mustache umami snackwave tilde chillwave ugh. Pour-over meditation PBR&amp;B pickled ennui celiac mlkshk freegan photo booth af fingerstache pitchfork.</p>
        <div class="flex justify-center">
          <button class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg"><a href="http://127.0.0.1:8000/admin/">Admin</a></button>
          <button class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg"><a href="{% url 'leads:lead_list' %}">Check Our Leads</a></button>
        </div>
      </div>
    </div>
  </section>
    <div>
        
        <div>
            
        </div>
        <div>
            
        </div>
    </div>

{% endblock %}

templates/navbar.html
<header class="text-gray-600 body-font">
    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
      <a class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0" href="{% url 'home' %}">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
          <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
        </svg>
        <span class="ml-3 text-xl">DJANGO CRM</span>
        
      </a>
      <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
        {% if request.user.is_authenticated %}
          {% if request.user.is_superuser %}
            <a class="mr-5 hover:text-gray-900" href="http://127.0.0.1:8000/admin/">DJAdmin</a>
          {% endif %}
        <a class="mr-5 hover:text-gray-900" href="{% url 'leads:lead_list' %}">Leads</a>
        <a class="mr-5 hover:text-gray-900" href="{% url 'leads:category_list' %}">Categories</a>
        {% if request.user.is_organizer %}
          <a class="mr-5 hover:text-gray-900" href="{% url 'agents:agent_list' %}">Agents</a>
        {% endif %}
        {% else %}
        <a class="mr-5 hover:text-gray-900" href="{% url 'signup' %}">Signup</a>
        {% endif %}
      </nav>
      {% if request.user.is_authenticated %}
      <a class="mr-5 text-purple-600" href="#">{{ request.user.username }}</a>
      <a href="{% url 'logout' %}" class="ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0"><form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <button type="submit">logout</button>
      </form>
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% else %}
      <a href="{% url 'login' %}" class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
          <path d="M5 12h14M12 5l7 7-7 7"></path>
        </svg>
      </a>
      {% endif %}
    </div>
  </header>

templates/scripts.html
{% load static %}

<script src="{% static 'js/main.js' %}">

</script>